LEADER_ENABLE = yes
NRKO_ENABLE = yes
UNICODE_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
TAP_DANCE_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no

